apiVersion: apps/v1
kind: Deployment

metadata:
  name: gateway-deployment

spec:
  selector:
    matchLabels:
      app : gateway
  template:
    labels:
      app : gateway
    spec:
      containers:
        - name: gateway
          image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/devops-portfolio-product:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "250m"
              memory: "256MI"

