apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-deployment

spec:
  selector:
    matchLabels:
      app : product
  template:
    metadata:
      labels:
        app : product
    spec:
      containers:
        - name: product
          image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/devops-portfolio-product:latest
          ports:
            - containerPort: 3002
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"