apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-deployment

spec:
  selector:
    matchLabels:
      app : user
  template:
    metadata:
      labels:
        app : user
    spec:
      containers:
        - name: user
          image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/devops-portfolio-product:latest
          ports:
            - containerPort: 3001
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"